controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home_index:
    path: /
    controller: App\Controller\HomeController::homeIndex

home_deux_index:
    path: /deux
    controller: App\Controller\HomeController::homeDeuxIndex